version: '3'
services:
  web:
    image: "uidesign"
    build: .
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
